;(function(){var dfltPluginCfg={"sourceFile":"download","info":true};var dfltGlobalCfg={"site":592858,"log":"","logSSL":"","domain":"","collectDomain":"logi242.xiti.com","collectDomainSSL":"logs1242.xiti.com","secure":true,"pixelPath":"/hit.xiti","disableCookie":false,"cookieSecure":false,"cookieDomain":"","preview":false,"plgs":["Campaigns","Clicks","ClientSideUserId","ContextVariables","IdentifiedVisitor","InternalSearch","MvTesting","Offline","OnSiteAds","Page","RichMedia"],"lazyLoadingPath":"","documentLevel":"document","redirect":false,"activateCallbacks":true,"medium":"","ignoreEmptyChapterValue":false,"base64Storage":false};(function(a){a.ATInternet=a.ATInternet||{};a.ATInternet.Tracker=a.ATInternet.Tracker||{};a.ATInternet.Tracker.Plugins=a.ATInternet.Tracker.Plugins||{}})(window);
    var Utils=function(){function a(k){var p=typeof k;if("object"!==p||null===k)return"string"===p&&(k='"'+k+'"'),String(k);var g,b,m=[],d=k&&k.constructor===Array;for(g in k)k.hasOwnProperty(g)&&(b=k[g],p=typeof b,"function"!==p&&"undefined"!==p&&("string"===p?b='"'+b.replace(/[^\\]"/g,'\\"')+'"':"object"===p&&null!==b&&(b=a(b)),m.push((d?"":'"'+g+'":')+String(b))));return(d?"[":"{")+String(m)+(d?"]":"}")}var e=this;e.cloneSimpleObject=function p(a,b){if("object"!==typeof a||null===a||a instanceof Date)return a;
        var m=new a.constructor,d;for(d in a)a.hasOwnProperty(d)&&(void 0===d||b&&void 0===a[d]||(m[d]=p(a[d])));return m};e.jsonSerialize=function(p){return"undefined"!==typeof JSON&&JSON.stringify?JSON.stringify(p):a(p)};e.jsonParse=function(a){try{return"undefined"!==typeof JSON&&JSON.parse?JSON.parse(a):null}catch(g){return null}};e.arrayIndexOf=function(a,g){return Array.indexOf?a.indexOf(g):function(a){if(null==this)throw new TypeError;var m=Object(this),d=m.length>>>0;if(0===d)return-1;var f=0;1<arguments.length&&
    (f=Number(arguments[1]),f!=f?f=0:0!=f&&Infinity!=f&&-Infinity!=f&&(f=(0<f||-1)*Math.floor(Math.abs(f))));if(f>=d)return-1;for(f=0<=f?f:Math.max(d-Math.abs(f),0);f<d;f++)if(f in m&&m[f]===a)return f;return-1}.apply(a,[g])};e.uuid=function(){return{v4:function(){return"xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g,function(a){var g=16*Math.random()|0;return("x"===a?g:g&3|8).toString(16)})},num:function(a){var g=new Date,b=function(a){a-=100*Math.floor(a/100);return 10>a?"0"+a:String(a)};return b(g.getHours())+
            ""+b(g.getMinutes())+""+b(g.getSeconds())+""+function(a){return Math.floor((9*Math.random()+1)*Math.pow(10,a-1))}(a-6)}}};e.getObjectKeys=function(a){var g=[],b;for(b in a)a.hasOwnProperty(b)&&g.push(b);return g};e.completeFstLevelObj=function(a,g,b){if(a){if(g)for(var m in g)!g.hasOwnProperty(m)||a[m]&&!b||(a[m]=g[m])}else a=g;return a};e.isPreview=function(){return window.navigator&&"preview"===window.navigator.loadPurpose};e.isPrerender=function(a){var g,b=!1,m=["webkit","ms"];if("prerender"===
        document.visibilityState)g="visibilitychange";else for(var d=0;d<m.length;d++)"prerender"===document[m[d]+"VisibilityState"]&&(g=m[d]+"visibilitychange");if("undefined"!==typeof g){var f=function(b){a(b);e.removeEvtListener(document,g,f)};e.addEvtListener(document,g,f);b=!0}return b};var h=e.addEvtListener=function(a,g,b){a.addEventListener?a.addEventListener(g,b,!1):a.attachEvent&&a.attachEvent("on"+g,b)},c=e.removeEvtListener=function(a,g,b){a.removeEventListener?a.removeEventListener(g,b,!1):a.detachEvent&&
        a.detachEvent("on"+g,b)};e.loadScript=function(a,g){var b;g=g||function(){};b=document.createElement("script");b.type="text/javascript";b.src=a.url;b.async=!1;b.defer=!1;b.onload=b.onreadystatechange=function(a){a=a||window.event;if("load"===a.type||/loaded|complete/.test(b.readyState)&&(!document.documentMode||9>document.documentMode))b.onload=b.onreadystatechange=b.onerror=null,g(null,a)};b.onerror=function(a,f,m){b.onload=b.onreadystatechange=b.onerror=null;g({msg:"script not loaded",event:a})};
        var m=document.head||document.getElementsByTagName("head")[0];m.insertBefore(b,m.lastChild)};e.hashcode=function(a){var g=0;if(0===a.length)return g;for(var b=0;b<a.length;b++)var m=a.charCodeAt(b),g=(g<<5)-g+m,g=g|0;return g};e.setLocation=function(a){var g=a.location;a=window[a.target]||window;g&&(a.location.href=g)};e.dispatchCallbackEvent=function(a){var g;"function"===typeof window.Event?g=new Event("ATCallbackEvent"):(g=document.createEvent("Event"),g.initEvent&&g.initEvent("ATCallbackEvent",
        !0,!0));g&&(g.name=a,document.dispatchEvent(g))};e.addCallbackEvent=function(a){h(document,"ATCallbackEvent",a)};(function(){function a(g,b){b=b||{bubbles:!1,cancelable:!1,detail:void 0};var m=document.createEvent("CustomEvent");m.initCustomEvent(g,b.bubbles,b.cancelable,b.detail);return m}if("function"===typeof window.CustomEvent)return!1;a.prototype=window.Event.prototype;window.CustomEvent=a})();e.addOptOutEvent=function(a,g){e.ATOptOutEvent=new CustomEvent("ATOptOutEvent",{detail:{name:"clientsideuserid",
            id:g}});h(document,"ATOptOutEvent",a)};e.removeOptOutEvent=function(a){c(document,"ATOptOutEvent",a)};e.dispatchOptOutEvent=function(a){e.optedOut=a;e.ATOptOutEvent=e.ATOptOutEvent||new CustomEvent("ATOptOutEvent",{detail:{name:"clientsideuserid",id:-1}});document.dispatchEvent(e.ATOptOutEvent)};e.userOptedOut=function(){e.dispatchOptOutEvent(!0)};e.userOptedIn=function(){e.dispatchOptOutEvent(!1)};e.isOptedOut=function(){return!!e.optedOut};e.optedOut=null;e.ATOptOutEvent=null};
    window.ATInternet.Utils=new Utils;
    var BuildManager=function(a){var e=this,h=function(a,b,f){a="&"+a+"=";return{param:a,paramSize:a.length,str:b,strSize:b.length,truncate:f}},c=function(b,d){var f="",k=0,n=!0,l;for(l in b)if(b.hasOwnProperty(l)){var q=b[l];if(q){var n=!1,g=d-k;if(q.strSize+q.paramSize<g)f+=q.param+q.str,k+=q.strSize+q.paramSize,b[l]=void 0,n=!0;else{q.truncate?(f+=q.param+q.str.substr(0,g),b[l].str=q.str.substr(g,q.strSize-1),b[l].strSize=b[l].str.length):q.strSize+q.paramSize>d&&(a.emit("Tracker:Hit:Build:Error",
        {lvl:"ERROR",msg:'Too long parameter "'+q.param+'"',details:{value:q.str}}),b[l].str=b[l].str.substr(0,d-q.paramSize-1),b[l].strSize=b[l].str.length);break}}else n=!0}return[f,n?null:b]},k=["ati","atc","pdtl","stc","dz"],p=function(b,d,f){var g=function(a){if(a==={})return"";var f=[],l;l={};var b=0,d=!1,n=void 0,g,e,r;for(r in a)if(a.hasOwnProperty(r)){var m=a[r].value;"function"===typeof m&&(m=m());m=m instanceof Array?m.join(a[r].options.separator||","):"object"===typeof m?window.ATInternet.Utils.jsonSerialize(m):
        "undefined"===typeof m?"undefined":m.toString();a[r].options.encode&&(m=encodeURIComponent(m));var p=h(r,m,-1<window.ATInternet.Utils.arrayIndexOf(k,r)),b=b+(p.paramSize+p.strSize);if(a[r].options.last)1490<m.length&&m.substr(0,1490),g=r,e=p;else if(l[r]=p,1500<l[r].paramSize+l[r].strSize&&!l[r].truncate){d=!0;n=r;break}}g&&(l[g]=e);l=[l,b,d,n];a=l[0];if(l[2])l=l[3],a=a[l],a.str=a.str.substr(0,1450),a.strSize=1450,b={},b.mherr=h("mherr","1",!1),b[l]=a,f.push(c(b,1500)[0]);else if(l=c(a,1500),null===
    l[1])f=l[0];else for(f.push(l[0]);null!==l[1];)l=c(a,1500),f.push(l[0]);return f},n="";a.buffer.presentInFilters(d,"hitType")||(d=a.buffer.addInFilters(d,"hitType",["page"]));d=a.buffer.addInFilters(d,"hitType",["all"]);var l;if(b){d=a.buffer.addInFilters(d,"permanent",!0);d=a.buffer.get(d,!0);for(l in b)b.hasOwnProperty(l)&&(d[l]={value:b[l],options:{}});n=g(d)}else for(l in d=a.buffer.get(d,!0),n=g(d),d)d.hasOwnProperty(l)&&!d[l].options.permanent&&a.buffer.del(l);f&&f(n)},g=function(b){var d=a.getConfig("secure"),
        f="https:"===document.location.protocol,k=d||f,f="",f=k?a.getConfig("logSSL"):a.getConfig("log"),n=a.getConfig("domain"),f=f&&n?f+"."+n:k?a.getConfig("collectDomainSSL"):a.getConfig("collectDomain"),k=a.getConfig("baseURL");(n=a.getConfig("pixelPath"))&&"/"!==n.charAt(0)&&(n="/"+n);var l=a.getConfig("site");(k||f&&n)&&l?b&&b(null,(k?k:(d?"https://":"//")+f+n)+("?s="+l)):b&&b({message:"Config error"})},b=function(a,b,f){g(function(k,n){k?f&&f(k):p(a,b,function(a){var b=[],d=ATInternet.Utils.uuid().num(13);
        if(a instanceof Array)if(1===a.length)b.push(n+"&mh=1-2-"+d+a[0]);else for(var k=1;k<=a.length;k++)b.push(n+"&mh="+k+"-"+a.length+"-"+d+a[k-1]);else b.push(n+a);f&&f(null,b)})})};e.send=function(k,d,f){b(k,d,function(b,d){if(b)a.emit("Tracker:Hit:Build:Error",{lvl:"ERROR",msg:b.message,details:{hits:d}});else for(var l=0;l<d.length;l++)e.sendUrl(d[l],f)})};e.sendUrl=function(b,d){var f=function(b,f){return function(){return function(q){a.emit(b,{lvl:-1===b.indexOf("Error")?"INFO":"ERROR",details:{hit:f,
            event:q}});d&&d()}}()},k=new Image;k.onload=f("Tracker:Hit:Sent:Ok",b);k.onerror=f("Tracker:Hit:Sent:Error",b);k.src=b}},TriggersManager=function(){function a(a,e,g){for(var b=[],c=0;c<a.length;c++)a[c].callback(e,g),a[c].singleUse||b.push(a[c]);return b}function e(a,c,g,b){var m=a.shift();if("*"===m)return c["*"]=c["*"]||[],c["*"].push({callback:g,singleUse:b}),c["*"].length-1;if(0===a.length)return e([m,"*"],c,g,b);c["*"]=c["*"]||[];c[m]=c[m]||{};return e(a,c[m],g,b)}function h(k,c,g,b){var e=c.shift();
        "*"!==e&&(0===c.length?h(k,[e,"*"],g,b):g[e]&&(g[e]["*"]=a(g[e]["*"],k,b),h(k,c,g[e],b)))}var c={};this.on=function(a,p,g){g=g||!1;return e(a.split(":"),c,p,g)};this.emit=function(k,e){c["*"]&&(c["*"]=a(c["*"],k,e));h(k,k.split(":"),c,e)}},PluginsManager=function(a){var e={},h={},c=0,k={},p=0,g=this.unload=function(b){e[b]?(e[b]=void 0,a.emit("Tracker:Plugin:Unload:"+b+":Ok",{lvl:"INFO"})):a.emit("Tracker:Plugin:Unload:"+b+":Error",{lvl:"ERROR",msg:"not a known plugin"});return a},b=this.load=function(b,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   f){"function"===typeof f?"undefined"===typeof a.getConfig.plgAllowed||0===a.getConfig.plgAllowed.length||-1<a.getConfig.plgAllowed.indexOf(b)?(e[b]=new f(a),h[b]&&e[b]&&(h[b]=!1,c--,e[b+"_ll"]&&g(b+"_ll"),0===c&&a.emit("Tracker:Plugin:Lazyload:File:Complete",{lvl:"INFO",msg:"LazyLoading triggers are finished"})),a.emit("Tracker:Plugin:Load:"+b+":Ok",{lvl:"INFO"})):a.emit("Tracker:Plugin:Load:"+b+":Error",{lvl:"ERROR",msg:"Plugin not allowed",details:{}}):a.emit("Tracker:Plugin:Load:"+b+":Error",{lvl:"ERROR",
        msg:"not a function",details:{obj:f}});return a},m=this.isLazyloading=function(a){return a?!0===h[a]:0!==c},d=function(a){return!e[a]&&!m(a)&&(e[a+"_ll"]?!0:!1)},f=function(b){h[b]=!0;c++;ATInternet.Utils.loadScript({url:a.getConfig("lazyLoadingPath")+b+".js"})},r=function(a){return d(a)?(f(a),!0):!1},n=function(a){k[a]?k[a]++:k[a]=1;p++};this.isExecWaitingLazyloading=function(){return 0!==p};a.exec=this.exec=function(b,q,g,c){var r=null,h=function(a,b,f,l){b=b.split(".");e[a]&&e[a][b[0]]&&(r=1<b.length&&
    e[a][b[0]][b[1]]?e[a][b[0]][b[1]].apply(e[a],f):e[a][b[0]].apply(e[a],f));l&&l(r)},v=function(b,f,l,q){n(b);a.onTrigger("Tracker:Plugin:Load:"+b+":Ok",function(){h(b,f,l,function(f){k[b]--;p--;0===p&&a.emit("Tracker:Plugin:Lazyload:Exec:Complete",{lvl:"INFO",msg:"All exec waiting for lazyloading are done"});q&&q(f)})},!0)};d(b)?(v(b,q,g,c),f(b)):m(b)?v(b,q,g,c):h(b,q,g,c)};this.waitForDependencies=function(b,f){var d=function(a){for(var b={mcount:0,plugins:{}},f=0;f<a.length;f++)e.hasOwnProperty(a[f])||
    (b.mcount++,b.plugins[a[f]]=!0);return b}(b);if(0===d.mcount)a.emit("Tracker:Plugin:Dependencies:Loaded",{lvl:"INFO",details:{dependencies:b}}),f();else for(var k in d.plugins)d.plugins.hasOwnProperty(k)&&(a.emit("Tracker:Plugin:Dependencies:Error",{lvl:"WARNING",msg:"Missing plugin "+k}),a.onTrigger("Tracker:Plugin:Load:"+k,function(a,b){var l=a.split(":"),k=l[3];"Ok"===l[4]&&(d.plugins[k]=!1,d.mcount--,0===d.mcount&&f())},!0),r(k))};this.init=function(){for(var a in ATInternet.Tracker.pluginProtos)ATInternet.Tracker.pluginProtos.hasOwnProperty(a)&&
    b(a,ATInternet.Tracker.pluginProtos[a])}},CallbacksManager=function(a){var e={},h=this.load=function(c,k){"function"===typeof k?(new k(a),a.emit("Tracker:Callback:Load:"+c+":Ok",{lvl:"INFO",details:{obj:k}})):a.emit("Tracker:Callback:Load:"+c+":Error",{lvl:"ERROR",msg:"not a function",details:{obj:k}});return a};this.init=function(){if(a.getConfig("activateCallbacks")){var c=a.getConfig("callbacks");(function(){if("undefined"!==typeof c&&c.include instanceof Array)for(var a=0;a<c.include.length;a++)ATInternet.Callbacks&&
    ATInternet.Callbacks.hasOwnProperty(c.include[a])&&(e[c.include[a]]={"function":ATInternet.Callbacks[c.include[a]]},ATInternet.Tracker.callbackProtos[c.include[a]]||(ATInternet.Tracker.callbackProtos[c.include[a]]=e[c.include[a]]));else for(a in ATInternet.Callbacks)ATInternet.Callbacks.hasOwnProperty(a)&&(e[a]={"function":ATInternet.Callbacks[a]},ATInternet.Tracker.callbackProtos[a]||(ATInternet.Tracker.callbackProtos[a]=e[a]));if("undefined"!==typeof c&&c.exclude instanceof Array)for(a=0;a<c.exclude.length;a++)e[c.exclude[a]]&&
    (e[c.exclude[a]]=void 0);for(var p in e)e.hasOwnProperty(p)&&e[p]&&h(p,e[p]["function"])})();ATInternet.Utils.addCallbackEvent(function(a){if(a.name){var e=!0;"undefined"!==typeof c&&(c.include instanceof Array&&-1===ATInternet.Utils.arrayIndexOf(c.include,a.name)&&(e=!1),c.exclude instanceof Array&&-1!==ATInternet.Utils.arrayIndexOf(c.exclude,a.name)&&(e=!1));if(ATInternet.Callbacks&&ATInternet.Callbacks.hasOwnProperty(a.name)){var g={};g[a.name]={"function":ATInternet.Callbacks[a.name]};e&&h(a.name,
        g[a.name]["function"]);ATInternet.Tracker.callbackProtos[a.name]||(ATInternet.Tracker.callbackProtos[a.name]=g[a.name])}}})}}},BufferManager=function(a){var e={};this.set=function(a,c,g){g=g||{};g.hitType=g.hitType||["page"];e[a]={value:c,options:g}};var h=function(a,c,g){return(a=window.ATInternet.Utils.cloneSimpleObject(a[c]))&&!g?a.value:a},c=function p(a,b){if(!(a&&b instanceof Array&&a instanceof Array))return[];if(0===a.length)return b;var c=a[0],d,f=[],r=window.ATInternet.Utils.cloneSimpleObject(a);
        r.shift();for(var n=0;n<b.length;n++)if("object"!==typeof c[1])e[b[n]]&&e[b[n]].options[c[0]]===c[1]&&f.push(b[n]);else{d=c[1].length;for(var l=0;l<d;l++)if(e[b[n]]&&e[b[n]].options[c[0]]instanceof Array&&0<=window.ATInternet.Utils.arrayIndexOf(e[b[n]].options[c[0]],c[1][l])){f.push(b[n]);break}}return p(r,f)};this.get=function(a,g){var b={};if("string"===typeof a)b=h(e,a,g);else for(var m=c(a,window.ATInternet.Utils.getObjectKeys(e)),d=0;d<m.length;d++)b[m[d]]=h(e,m[d],g);return b};this.presentInFilters=
        function g(a,c){return a&&0!==a.length?a[0][0]===c?!0:g(a.slice(1),c):!1};this.addInFilters=function b(a,d,f,c){if(!a||0===a.length)return c?[]:[[d,f]];var n=a[0][0],l=a[0][1];n===d&&(l instanceof Array&&!(-1<window.ATInternet.Utils.arrayIndexOf(l,f[0]))&&l.push(f[0]),c=!0);return[[n,l]].concat(b(a.slice(1),d,f,c))};this.del=function(a){e[a]=void 0};this.clear=function(){e={}}},Tag=function(a,e,h){e=e||{};var c=this;c.version="5.13.1";var k=window.ATInternet.Utils.cloneSimpleObject(e);c.triggers=
        new TriggersManager(c);c.emit=c.triggers.emit;c.onTrigger=c.triggers.on;var p=window.ATInternet.Utils.cloneSimpleObject(dfltGlobalCfg)||{},g;for(g in a)a.hasOwnProperty(g)&&(p[g]=a[g]);c.getConfig=function(a){return p[a]};c.setConfig=function(a,g,d){void 0!==p[a]&&d||(c.emit("Tracker:Config:Set:"+a,{lvl:"INFO",details:{bef:p[a],aft:g}}),p[a]=g)};c.configPlugin=function(a,g,d){p[a]=p[a]||{};for(var f in g)g.hasOwnProperty(f)&&void 0===p[a][f]&&(p[a][f]=g[f]);d&&(d(p[a]),c.onTrigger("Tracker:Config:Set:"+
        a,function(a,b){d(b.details.aft)}));return p[a]};c.getContext=function(a){return k[a]};c.setContext=function(a,g){c.emit("Tracker:Context:Set:"+a,{lvl:"INFO",details:{bef:k[a],aft:g}});k[a]=g};c.delContext=function(a,g){c.emit("Tracker:Context:Deleted:"+a+":"+g,{lvl:"INFO",details:{key1:a,key2:g}});if(a)k.hasOwnProperty(a)&&(g?k[a]&&k[a].hasOwnProperty(g)&&(k[a][g]=void 0):k[a]=void 0);else if(g)for(var d in k)k.hasOwnProperty(d)&&k[d]&&k[d].hasOwnProperty(g)&&(k[d][g]=void 0)};c.plugins=new PluginsManager(c);
        c.buffer=new BufferManager(c);c.setParam=c.buffer.set;c.getParams=function(a){return c.buffer.get(a,!1)};c.getParam=c.buffer.get;c.delParam=c.buffer.del;c.builder=new BuildManager(c);c.sendHit=c.builder.send;c.sendUrl=c.builder.sendUrl;c.callbacks=new CallbacksManager(c);c.setParam("ts",function(){return(new Date).getTime()},{permanent:!0,hitType:["all"]});c.getConfig("disableCookie")&&c.setParam("idclient","Consent-NO",{permanent:!0,hitType:["all"]});c.getConfig("medium")&&c.setParam("medium",c.getConfig("medium"),
            {permanent:!0,hitType:["all"]});c.plugins.init();c.callbacks.init();ATInternet.Tracker.instances.push(c);c.emit("Tracker:Ready",{lvl:"INFO",msg:"Tracker initialized",details:{tracker:c,args:{config:a,context:e,callback:h}}});h&&h(c)};ATInternet.Tracker.Tag=Tag;ATInternet.Tracker.instances=[];ATInternet.Tracker.pluginProtos={};
    ATInternet.Tracker.addPlugin=function(a,e){e=e||ATInternet.Tracker.Plugins[a];if(!ATInternet.Tracker.pluginProtos[a]){ATInternet.Tracker.pluginProtos[a]=e;for(var h=0;h<ATInternet.Tracker.instances.length;h++)ATInternet.Tracker.instances[h].plugins.load(a,e)}};ATInternet.Tracker.delPlugin=function(a){if(ATInternet.Tracker.pluginProtos[a]){ATInternet.Tracker.pluginProtos[a]=void 0;for(var e=0;e<ATInternet.Tracker.instances.length;e++)ATInternet.Tracker.instances[e].plugins.unload(a)}};
    ATInternet.Tracker.callbackProtos={};
}).call(window);;(function(){var dfltPluginCfg={"lifetime":30,"lastPersistence":true,"listEventsForExec":[],"domainAttribution":true,"info":true};var dfltGlobalCfg={"visitLifetime":30,"redirectionLifetime":30};window.ATInternet.Tracker.Plugins.Campaigns=function(a){a.setConfig("visitLifetime",dfltGlobalCfg.visitLifetime,!0);a.setConfig("redirectionLifetime",dfltGlobalCfg.redirectionLifetime,!0);var e={},h,c;a.configPlugin("Campaigns",dfltPluginCfg||{},function(a){e=a});var k,p,g,b,m,d,f,r,n,l,q,y,z,u=function(b,f,l){var q=null;a.plugins.exec(b,f,l,function(a){q=a});return q},s=function(a,b){return u("Cookies",a,b)},v=function(a,b){return u("Utils",a,b)},x=function(a,b){var f=s(c,[a]);if(null!==f)return"object"===
    typeof f&&!(f instanceof Array);s(h,[a,{},b]);return!0},B=function(b,f){var l=a.getContext("campaigns")||{};l[b]=f;a.setContext("campaigns",l)},A=function(u){h="set"+(e.domainAttribution?"":"Private");c="get"+(e.domainAttribution?"":"Private");k=s(c,[["atredir","gopc"]]);p=s(c,[["atredir","gopc_err"]]);g=s(c,[["atredir","camp"]]);s("del",[["atredir","gopc"]]);s("del",[["atredir","gopc_err"]]);s("del",[["atredir","camp"]]);b=s(c,[["atsession","histo_camp"]]);m=s(c,[["atreman","camp"]]);d=s(c,[["atreman",
    "date"]]);var t=v("getLocation",[]);f=v("getQueryStringValue",["xtor",t]);r=v("getQueryStringValue",["xtdt",t]);n=v("getQueryStringValue",["xts",t]);l=a.getContext("forcedCampaign");q=!!a.getConfig("redirect");if(y=f&&r&&n?!0:!1)t=(new Date).getTime()/6E4,z=!q&&n!==a.getConfig("site")||0>t-r||t-r>=a.getConfig("visitLifetime")?!0:!1;t=l||g||f;if(q&&t&&x("atredir",{path:"/",end:a.getConfig("redirectionLifetime")})){s(h,[["atredir","camp"],t]);var A=t=!1;l||(g?(t=k,A=p):(y&&(t=!0),z&&(A=!0)));s(h,[["atredir",
    "gopc"],t]);s(h,[["atredir","gopc_err"],A])}!q&&m&&(B("xtor",m),t=(new Date).getTime()/36E5,t=Math.floor(t-d),B("roinbh",0<=t?t:0));q||(t=void 0,t=g?k?l||t:l||g:y?l||t:l||f||t,b&&b instanceof Array&&-1<b.indexOf(t)&&(t=void 0),t&&B("xto",t));if(!q&&!l){var w;g?p&&(w=g):z&&(w=f);w&&B("pgt",w)}q||!(w=g?l||g:l||f||void 0)||!l&&!g&&y&&z||!l&&g&&k&&p||((!b||b instanceof Array&&0>b.indexOf(w))&&x("atsession",{path:"/",session:60*a.getConfig("visitLifetime")})&&s(h,[["atsession","histo_camp"],b&&b.push(w)?
    b:[w]]),m&&!e.lastPersistence||!x("atreman",{path:"/",session:86400*e.lifetime})||(s(h,[["atreman","camp"],w]),s(h,[["atreman","date"],(new Date).getTime()/36E5])));a.emit("Campaigns:"+u,{lvl:"INFO"})};(function(){var b=["Cookies","Utils"];if(-1===ATInternet.Utils.arrayIndexOf(a.getConfig("plgs"),"BackwardCompat"))a.plugins.waitForDependencies(b,function(){A("process2:done")});else a.onTrigger("BackCampaigns:process2:done",function(f,l){a.plugins.waitForDependencies(b,function(){A("process1:done")})},
    !0)})()};window.ATInternet.Tracker.addPlugin("Campaigns");
}).call(window);;(function(){var dfltPluginCfg={"info":true};var dfltGlobalCfg={};window.ATInternet.Tracker.Plugins.Clicks=function(a){var e=function(a){var c="";switch(a){case "exit":c="S";break;case "download":c="T";break;case "action":c="A";break;case "navigation":c="N"}return c},h=function(c){var e=c.name;a.exec("Utils","manageChapters",[c,"chapter",3],function(a){e=a+(e?e:"")});return e},c=function(c){var p={p:h(c),s2:c.level2||"",click:e(c.type)||""},g=a.getContext("page")||{};p.pclick=h(g);p.s2click=g.level2||"";c.customObject&&a.exec("Utils","customObjectToString",[c.customObject],
    function(a){p.stc=a});a.sendHit(p,[["hitType",["click"]]],c.callback)};a.click={};a.clickListener=this.clickListener={};a.click.send=this.send=function(e){var h=!0;a.plugins.exec("TechClicks","manageClick",[e.elem,e.event],function(a){h=a});c(e);return h};a.clickListener.send=this.clickListener.send=function(e){if(e.elem){var h;a.plugins.exec("TechClicks","isFormSubmit",[e.elem],function(a){h=a?"submit":"click"});ATInternet.Utils.addEvtListener(e.elem,h,function(g){a.plugins.exec("TechClicks","manageClick",
    [e.elem,g]);c(e)})}};a.click.set=this.set=function(c){a.dispatchSubscribe("click");a.setContext("click",{name:h(c),level2:c.level2||"",customObject:c.customObject});a.setParam("click",e(c.type)||"",{hitType:["click"]})};a.click.onDispatch=this.onDispatch=function(c){var e={hitType:["click"]};a.setParam("p",a.getContext("click").name,e);a.setParam("s2",a.getContext("click").level2,e);var g=a.getContext("click").customObject;g&&a.setParam("stc",g,{hitType:["click"],encode:!0});g=a.getContext("page")||
    {};a.setParam("pclick",h(g),e);a.setParam("s2click",g.level2||"",e);a.sendHit(null,[["hitType",["click"]]],c);a.setContext("click",void 0)}};window.ATInternet.Tracker.addPlugin("Clicks");
}).call(window);;(function(){var dfltPluginCfg={"clientSideMode":"required","userIdCookieDuration":397,"userIdExpirationMode":"fixed","optOut":"OPT-OUT","userIdCookieName":"atuserid","optOutCookieName":"atoptedout","info":true};var dfltGlobalCfg={};window.ATInternet.Tracker.Plugins.ClientSideUserId=function(a){var e={},h=void 0,c=null,k=-1,p=!1;a.configPlugin("ClientSideUserId",dfltPluginCfg||{},function(a){e=a});var g=function(){h=a.getContext("userIdentifier");a.exec("Cookies","get",["atuserid"],function(a){c=a})},b=function(b,f,q){if("relative"===e.userIdExpirationMode||"fixed"===e.userIdExpirationMode&&null===c||q){var d=new Date;d.setTime(d.getTime()+864E5*e.userIdCookieDuration);a.exec("Cookies","set",[b,f,{end:d,path:"/"}]);a.exec("Cookies",
    "get",[b,!0],function(b){q||f===b||a.setParam("idclient",f+"-NO",{permanent:!0,hitType:["all"]})})}},m=function(f,l,q){a.setParam("idclient",f,{permanent:!0,hitType:["all"]});b(q,f,l)},d=function(){var b=!1,f=null,q=ATInternet.Utils.optedOut;!1===q&&(a.exec("Cookies","set",["atoptedout",null,{path:"/"}]),a.getParam("idclient")===e.optOut&&a.delParam("idclient"));a.exec("Cookies","get",["atoptedout",!0],function(a){f=a});if(!0===q||f===e.optOut)b=!0;b&&(ATInternet.Utils.optedOut=!0);return b},f=function(){g();
    var b,f=!1;if("required"===e.clientSideMode){if(b=navigator.userAgent,/Safari/.test(b)&&!/Chrome/.test(b)||/iPhone|iPod|iPad/.test(b))f=!0}else"always"===e.clientSideMode&&(f=!0);b=f;f="undefined"!==typeof h;p=d();if(b||f||p){var q="";b=!1;var r=e.userIdCookieName;p?(q=e.optOut,b=!0,r=e.optOutCookieName):a.getConfig("disableCookie")?(q=a.getParam("idclient"),b=!0):f?(q=h,b=!0):q=null!==c?c:ATInternet.Utils.uuid().v4();m(q,b,r)}a.emit("ClientSideUserId:Ready",{lvl:"INFO",details:{clientSideMode:e.clientSideMode,
            userIdCookieDuration:e.userIdCookieDuration,userIdExpirationMode:e.userIdExpirationMode,userIdFromContext:h,userIdFromCookie:c,userId:q}})},r=function(a){a&&(a=a.detail)&&"clientsideuserid"===a.name&&a.id===k&&f()};(function(){a.plugins.waitForDependencies(["Cookies"],function(){var a=ATInternet.Utils.uuid();k=parseInt(a.num(8));ATInternet.Utils.removeOptOutEvent(r);ATInternet.Utils.addOptOutEvent(r,k);f()})})();a.clientSideUserId={};a.clientSideUserId.set=function(a){var b=e.userIdCookieName;p&&
(a=e.optOut,b=e.optOutCookieName);m(a,!0,b)}};window.ATInternet.Tracker.addPlugin("ClientSideUserId");
}).call(window);;(function(){var dfltPluginCfg={"domainAttribution":true,"info":true};var dfltGlobalCfg={"redirectionLifetime":30};window.ATInternet.Tracker.Plugins.ContextVariables=function(a){var e="",h=null,c,k="",p="",g={};a.configPlugin("ContextVariables",dfltPluginCfg||{},function(a){g=a});a.setConfig("redirectionLifetime",dfltGlobalCfg.redirectionLifetime,!0);var b=function(b,f,d){var q=null;a.plugins.exec(b,f,d,function(a){q=a});return q},m=function(a,f){return b("Utils",a,f)},d=function(b,f){var d=null;a.plugins.exec("Cookies",b,f,function(a){d=a});return d},f=function(){a.setParam("hl",function(){var a=new Date;return a.getHours()+
    "x"+a.getMinutes()+"x"+a.getSeconds()},{permanent:!0,hitType:["all"]})};a.plugins.waitForDependencies(["Cookies","Utils"],function(){k="set"+(g.domainAttribution?"":"Private");p="get"+(g.domainAttribution?"":"Private");var b=m("getLocation",[]);e=m("getQueryStringValue",["xtref",b]);void 0===e&&(e="");c=a.getContext("forcedReferer");if(a.getConfig("redirect")){var b=m("getDocumentLevel",[]),b=c?c:null!==e?e:b.referrer||"acc_dir",n;if(n=b){n={path:"/",end:a.getConfig("redirectionLifetime")};var l=
    d(p,["atredir"]);null!==l?n="object"===typeof l&&!(l instanceof Array):(d(k,["atredir",{},n]),n=!0)}n&&d(k,[["atredir","ref"],b])}else{h=d(p,[["atredir","ref"]]);d("del",[["atredir","ref"]]);a.setParam("vtag",a.version,{permanent:!0,hitType:["all"]});a.setParam("ptag","js",{permanent:!0,hitType:["all"]});b="";try{b+=window.screen.width+"x"+window.screen.height+"x"+window.screen.pixelDepth+"x"+window.screen.colorDepth}catch(q){}a.setParam("r",b,{permanent:!0,hitType:["all"]});b="";window.innerWidth?
    b+=window.innerWidth+"x"+window.innerHeight:document.body&&document.body.offsetWidth&&(b+=document.body.offsetWidth+"x"+document.body.offsetHeight);a.setParam("re",b,{permanent:!0,hitType:["all"]});f();a.setParam("lng",navigator.language||navigator.userLanguage,{permanent:!0,hitType:["all"]});b=ATInternet.Utils.uuid().num(13);a.setParam("idp",b,{permanent:!0,hitType:["page","clickzone"]});a.setParam("jv",navigator.javaEnabled()?"1":"0",{hitType:["page"]});b=m("getDocumentLevel",[]);a.setParam("ref",
    (c?c:"acc_dir"===e?"":null!==e?e:"acc_dir"===h?"":h?h:b.referrer).replace(/[<>]/g,"").substring(0,1600).replace(/&/g,"$"),{permanent:!0,last:!0,hitType:["page"]})}a.emit("ContextVariables:Ready",{lvl:"INFO"})})};window.ATInternet.Tracker.addPlugin("ContextVariables");
}).call(window);;(function(){var dfltPluginCfg={"info":false};var dfltGlobalCfg={};window.ATInternet.Tracker.Plugins.Cookies=function(a){var e={},h={_keyStr:"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=",encode:function(a){var b="",f,d,c,g,e,n,k=0;for(a=h._utf8_encode(a);k<a.length;)f=a.charCodeAt(k++),d=a.charCodeAt(k++),c=a.charCodeAt(k++),g=f>>2,f=(f&3)<<4|d>>4,e=(d&15)<<2|c>>6,n=c&63,isNaN(d)?e=n=64:isNaN(c)&&(n=64),b=b+this._keyStr.charAt(g)+this._keyStr.charAt(f)+this._keyStr.charAt(e)+this._keyStr.charAt(n);return b},decode:function(a){var b="",f,d,c,
        g,e,n=0;for(a=a.replace(/[^A-Za-z0-9\+\/\=]/g,"");n<a.length;)f=this._keyStr.indexOf(a.charAt(n++)),d=this._keyStr.indexOf(a.charAt(n++)),g=this._keyStr.indexOf(a.charAt(n++)),e=this._keyStr.indexOf(a.charAt(n++)),f=f<<2|d>>4,d=(d&15)<<4|g>>2,c=(g&3)<<6|e,b+=String.fromCharCode(f),64!=g&&(b+=String.fromCharCode(d)),64!=e&&(b+=String.fromCharCode(c));return b=h._utf8_decode(b)},_utf8_encode:function(a){a=a.replace(/\r\n/g,"\n");for(var b="",f=0;f<a.length;f++){var d=a.charCodeAt(f);128>d?b+=String.fromCharCode(d):
        (127<d&&2048>d?b+=String.fromCharCode(d>>6|192):(b+=String.fromCharCode(d>>12|224),b+=String.fromCharCode(d>>6&63|128)),b+=String.fromCharCode(d&63|128))}return b},_utf8_decode:function(a){for(var b="",f=0,d,c,g;f<a.length;)d=a.charCodeAt(f),128>d?(b+=String.fromCharCode(d),f++):191<d&&224>d?(c=a.charCodeAt(f+1),b+=String.fromCharCode((d&31)<<6|c&63),f+=2):(c=a.charCodeAt(f+1),g=a.charCodeAt(f+2),b+=String.fromCharCode((d&15)<<12|(c&63)<<6|g&63),f+=3);return b}},c=this.getCookie=function(b){return!a.getConfig("disableCookie")&&
b&&"string"===typeof b&&(b=RegExp("(?:^| )"+b+"=([^;]+)").exec(document.cookie)||null)?(b=b[1],b=a.getConfig("base64Storage")?h.decode(b):decodeURIComponent(b),b):null},k=this.setCookie=function(b,f,d){if(!a.getConfig("disableCookie")&&b&&"string"===typeof b&&"string"===typeof f){var c=a.getConfig("cookieDomain");b+="=";f=a.getConfig("base64Storage")?h.encode(f):encodeURIComponent(f);f=b+f;b=!1;if(d){b=d.secure;var g=d.end,e=d.domain;d=d.path;g&&("function"===typeof g.toGMTString?f+=";expires="+g.toGMTString():
    "number"===typeof g&&(f+=";max-age="+g.toString()));e?f+=";domain="+e:c&&(f+=";domain="+c);d&&"string"===typeof d&&(f+=";path="+d)}c=a.getConfig("cookieSecure")||b;document.cookie=f+(c&&"boolean"===typeof c?";secure":"");return!0}return null},p=function(a){var b=null;(a=c(a))&&(b=ATInternet.Utils.jsonParse(a));return b},g=function(a){return k(a.name,ATInternet.Utils.jsonSerialize(a),a.options)?a:null},b=function(a,b,f){var d=null;if(!f&&e[a])d=e[a];else if(d=p(a))d.options.session&&g(d),e[a]=d;return d?
    b?(a=null,!d||"object"!==typeof d.val||d.val instanceof Array||void 0===d.val[b]||(a=d.val[b]),a):d.val:null},m=function(a,b,f,d){var c=null;if(b){if(c=p(a))d=c,!d||"object"!==typeof d.val||d.val instanceof Array?c=null:(d.val[b]=f,c=d),c&&(c=g(c))}else b=d=d||{},d={},d.name=a,d.val=f,b.session&&"number"===typeof b.session&&(b.end=b.session),d.options=b,c=g(d);c&&(e[a]=c);return c?c.val:null},d=function(a,b){b?m(a,b,void 0):(e[a]=void 0,k(a,"",{end:0}))};a.cookies={};var f=a.cookies.get=this.get=
    function(a,f){f=f||!1;return a instanceof Array&&2===a.length?b(a[0],a[1],f):b(a,void 0,f)};a.cookies.getPrivate=this.getPrivate=function(b,d){d=d||!1;b instanceof Array?b[0]+=a.getConfig("site"):b+=a.getConfig("site");return f(b,d)};var r=a.cookies.set=this.set=function(a,b,f){return a instanceof Array?m(a[0],a[1],b):m(a,null,b,f)};a.cookies.setPrivate=this.setPrivate=function(b,f,d){b instanceof Array?b[0]+=a.getConfig("site"):b+=a.getConfig("site");return r(b,f,d)};var n=a.cookies.del=this.del=
    function(a){return a instanceof Array?d(a[0],a[1]):d(a)};a.cookies.delPrivate=this.delPrivate=function(b){b instanceof Array?b[0]+=a.getConfig("site"):b+=a.getConfig("site");return n(b)};a.cookies.cacheInvalidation=this.cacheInvalidation=function(){e={}}};window.ATInternet.Tracker.addPlugin("Cookies");
}).call(window);;(function(){var dfltPluginCfg={"lifetime":182,"domainAttribution":true,"info":true};var dfltGlobalCfg={"redirectionLifetime":30};window.ATInternet.Tracker.Plugins.IdentifiedVisitor=function(a){var e=null,h=null,c=null,k=null,p="",g="",b=null,m=null,d="",f="",r={};a.configPlugin("IdentifiedVisitor",dfltPluginCfg||{},function(a){r=a});a.setConfig("redirectionLifetime",dfltGlobalCfg.redirectionLifetime,!0);var n=function(b,f,d){var c=null;a.plugins.exec(b,f,d,function(a){c=a});return c},l=function(a,b){return n("Utils",a,b)},q=function(b,f){var d=null;a.plugins.exec("Cookies",b,f,function(a){d=a});return d},y=function(a,b){var c=
    q(f,[a]);if(null!==c)return"object"===typeof c&&!(c instanceof Array);q(d,[a,{},b]);return!0},z=function(a,b){y("atidvisitor",{path:"/",session:86400*r.lifetime})&&q(d,[["atidvisitor",a],b])},u=function(b,f){a.setParam(b,f,{hitType:["all"],permanent:!0});z(b,f)},s=function(){var f=function(a,b){/-/.test(b)?(a.category=b.split("-")[0],a.id=b.split("-")[1]):a.id=b},d={category:"",id:""};f(d,g||m);var n={category:"",id:""};f(n,p||b);n.id?(n.category&&u("ac",n.category),u("at",n.id)):e&&(a.setParam("at",
    e,{hitType:["all"],permanent:!0}),c&&a.setParam("ac",c,{hitType:["all"],permanent:!0}));d.id?(d.category&&u("ac",d.category),u("an",d.id)):h&&a.setParam("anc",c+"-"+h,{hitType:["all"],permanent:!0})};a.plugins.waitForDependencies(["Cookies","Utils"],function(){d="set"+(r.domainAttribution?"":"Private");f="get"+(r.domainAttribution?"":"Private");var n=l("getLocation",[]);p=l("getQueryStringValue",["xtat",n]);g=l("getQueryStringValue",["xtan",n]);a.getConfig("redirect")?(p||g)&&y("atredir",{path:"/",
    end:a.getConfig("redirectionLifetime")})&&(g&&q(d,[["atredir","an"],g]),p&&q(d,[["atredir","at"],p])):(b=q(f,[["atredir","at"]]),m=q(f,[["atredir","an"]]),q("del",[["atredir","at"]]),q("del",[["atredir","an"]]),e=q(f,[["atidvisitor","at"]]),h=q(f,[["atidvisitor","an"]]),c=q(f,[["atidvisitor","ac"]]),k=q(f,[["atidvisitor","vrn"]]),s(),n="-"+a.getConfig("site")+"-",RegExp(n).test(k)||(k=(k||"")+n,z("vrn",k),n=a.getContext("page")||{},n.vrn=1,a.setContext("page",n)));a.emit("IdentifiedVisitor:Ready",
    {lvl:"INFO",details:{cookieRedirectTextual:b,cookieRedirectNumeric:m,cookieTextual:e,cookieNumeric:h,cookieCategory:c,cookieVrn:k}})});a.identifiedVisitor={};a.identifiedVisitor.set=this.set=function(a){var b=a.id;a=a.category;"number"===typeof b?u("an",b.toString()):u("at",b);"undefined"!==typeof a&&u("ac",a)};a.identifiedVisitor.unset=this.unset=function(){for(var b=["an","at","ac"],f=0;f<b.length;f++)a.exec("Cookies","set",[["atidvisitor",b[f]],void 0]),a.delParam(b[f]);a.delParam("anc")}};window.ATInternet.Tracker.addPlugin("IdentifiedVisitor");
}).call(window);;(function(){var dfltPluginCfg={"urlKeyword":"","urlResultPageNumber":"","urlResultPosition":"","info":true};var dfltGlobalCfg={};window.ATInternet.Tracker.Plugins.InternalSearch=function(a){var e={};a.configPlugin("InternalSearch",dfltPluginCfg||{},function(a){e=a});var h=function(c){var e={np:"undefined"!==typeof c.resultPageNumber?c.resultPageNumber:"1",click:"IS"};c.hasOwnProperty("keyword")&&(e.mc=c.keyword);c.hasOwnProperty("resultPosition")&&(e.mcrg=c.resultPosition);a.sendHit(e,[["hitType",["InternalSearch"]]],c.callback)};a.internalSearch={};a.internalSearch.set=this.set=function(c){var e={},h=e;c.hasOwnProperty("keyword")&&
(h.keyword=c.keyword);h=e;c.hasOwnProperty("resultPageNumber")&&(h.resultPageNumber=c.resultPageNumber);c=a.getContext("InternalSearch")||{};e=ATInternet.Utils.completeFstLevelObj(e,c);"undefined"===typeof e.resultPageNumber&&(e.resultPageNumber="1");a.setContext("InternalSearch",e)};a.internalSearch.send=this.send=function(c){var e=!0;a.plugins.exec("TechClicks","manageClick",[c.elem,c.event],function(a){e=a});h(c);return e};a.plugins.waitForDependencies(["Utils"],function(){var c;if(e.urlKeyword){var k=
    document.location.href;c={};a.plugins.exec("Utils","getQueryStringValue",[e.urlKeyword,k],function(h){h&&(c.keyword=h);e.urlResultPageNumber&&a.plugins.exec("Utils","getQueryStringValue",[e.urlResultPageNumber,k],function(a){c.resultPageNumber=a||"1"})})}c&&a.setContext("InternalSearch",c);a.emit("InternalSearch:Ready",{lvl:"INFO",details:{config:{urlKeyword:e.urlKeyword,urlResultPageNumber:e.urlResultPageNumber},url:k,data:c}})})};window.ATInternet.Tracker.addPlugin("InternalSearch");
}).call(window);;(function(){var dfltPluginCfg={"info":true};var dfltGlobalCfg={};window.ATInternet.Tracker.Plugins.MvTesting=function(a){var e=0,h=function(a,b){var c="";a.hasOwnProperty(b)&&(c=a[b],c=void 0===c?"":c+"");return c},c=function(a){for(var b in a)if(a.hasOwnProperty(b))return!1;return!0},k=function(a){return"object"===typeof a&&!(a instanceof Array)},p=function(c){var b=c.name;a.exec("Utils","manageChapters",[c,"chapter",3],function(a){b=a+(b?b:"")});return b};a.mvTesting={};a.mvTesting.set=function(e){if(k(e)&&!c(e)){a.dispatchSubscribe("mvTesting");var b=h(e,"test"),
    m=h(e,"waveId");e=h(e,"creation");a.setParam("abmvc",b+"-"+m+"-"+e,{hitType:["mvtesting"]})}};a.mvTesting.add=function(g){if(k(g)&&!c(g)){a.dispatchSubscribe("mvTesting");var b=h(g,"variable");g=h(g,"version");e++;a.setParam("abmv"+e,b+"-"+g,{hitType:["mvtesting"]})}};a.mvTesting.onDispatch=function(c){var b=a.getContext("page")||{};a.setParam("p",p(b),{hitType:["mvtesting"]});a.setParam("s2",b.level2||"",{hitType:["mvtesting"]});a.setParam("type","mvt",{hitType:["mvtesting"]});a.sendHit(null,[["hitType",
    ["mvtesting"]]],c)}};window.ATInternet.Tracker.addPlugin("MvTesting");
}).call(window);;(function(){var dfltPluginCfg={"storageCapacity":1,"storageMode":"required","timeout":500,"info":true};var dfltGlobalCfg={};window.ATInternet.Tracker.Plugins.Offline=function(a){var e={};a.configPlugin("Offline",dfltPluginCfg||{},function(a){e=a});var h=function(){var a=localStorage.getItem("ATOffline"),b={hits:[],length:0};if(a){var c=ATInternet.Utils.jsonParse(a)||{hits:[]};b.hits=c.hits;b.length=a.length}return b},c=function(a){try{localStorage.setItem("ATOffline",ATInternet.Utils.jsonSerialize(a))}catch(b){}},k=function(){return h().hits},p=function(a){if(a){a=a.split(/&ref=\.*/i);var b="&cn=offline&olt="+String(Math.floor((new Date).getTime()/
    1E3));a=a[0]+b+"&ref="+(a[1]||"")}return a},g=function(a){var b=h(),g=a.length,n=!0;if(4*((b.length||11)+g)>1048576*e.storageCapacity){var n=!1,k=b.hits.shift();if("undefined"!==typeof k)for(var n=!0,q=k.length;q<g;)if(k=b.hits.shift(),"undefined"!==typeof k)q+=k.length;else{n=!1;break}}n&&(b.hits.push(a),c({hits:b.hits}))},b=function(d,f){if(navigator.onLine){var r=k();if(0<r.length){var n=r.shift();c({hits:r});a.onTrigger("Tracker:Hit:Sent:Ok",function(){b(d,f)},!0);a.onTrigger("Tracker:Hit:Sent:Error",
    function(){b(d,f)},!0);a.sendUrl(n)}else if(d){var l=null;a.plugins.exec("Utils","getQueryStringValue",["a",d],function(a){l=a});l?setTimeout(function(){a.sendUrl(d,f)},e.timeout):a.sendUrl(d,f)}}else d&&(g(p(d)),f&&f())},m=function(d){a.builder.sendUrl=function(a,c){d||!navigator.onLine?(g(p(a)),c&&c()):b(a,c)}};a.offline={};a.offline.getLength=function(){return 4*h().length};a.offline.remove=function(){c({hits:[]})};a.offline.get=k;a.offline.send=function(){b(null,null)};a.plugins.waitForDependencies(["Utils"],
    function(){var b;try{var f=window.localStorage;f.setItem("__storage_test__","__storage_test__");f.removeItem("__storage_test__");b=!0}catch(c){b=!1}f=navigator.onLine;b&&"undefined"!==typeof f&&("required"===e.storageMode?m(!1):"always"===e.storageMode&&m(!0));a.emit("Offline:Ready",{lvl:"INFO",details:{isLocalStorageAvailable:b,storageMode:e.storageMode,isOnline:f}})})};window.ATInternet.Tracker.addPlugin("Offline");
}).call(window);;(function(){var dfltPluginCfg={"info":true};var dfltGlobalCfg={};window.ATInternet.Tracker.Plugins.OnSiteAds=function(a){var e="",h=function(b){var d=b.name;a.exec("Utils","manageChapters",[b,"chapter",3],function(a){d=a+(d?d:"")});return d},c=function(a,b){return a[b]?a[b]:""},k=function(a,b){var d=c(a,b);if(d){var e=c(a,"prefix");if(d.campaignId){var e=e||"PUB",g=c(d,"campaignId"),k=c(d,"creation"),h=c(d,"variant"),m=c(d,"format"),p=c(d,"generalPlacement"),v=c(d,"detailedPlacement"),x=c(d,"advertiserId"),d=c(d,"url");return e+"-"+g+"-"+k+"-"+h+"-"+m+"-"+p+"-"+
    v+"-"+x+"-"+d}if(d.adId)return e=e||"INT",g=c(d,"adId"),k=c(d,"format"),d=c(d,"productId"),e+"-"+g+"-"+k+"||"+d}return""},p=function(b){var d=a.getContext("page")||{};a.sendHit({atc:k(b,"click"),type:"AT",patc:h(d),s2atc:d.level2||"",stc:b.customObject||""},[["hitType",["onSiteAdsClick"]]],b.callback)},g=function(b){a.sendHit({ati:k(b,"impression"),type:"AT",stc:b.customObject||""},[["hitType",["onSiteAdsImpression"]]],b.callback)},b=function(b,d){var c=a.buffer.get("ati",!0)||{};c.value="string"===
typeof c.value?[c.value]:c.value||[];c.options=c.options||{hitType:[d,"page"]};c.value.push(b);a.buffer.set("ati",c.value,c.options)},m=function(b,d){b.click?a.setParam("atc",k(b,"click"),{hitType:[d,"page"]}):b.impression&&a.setParam("ati",k(b,"impression"),{hitType:[d,"page"]});if(b.customObject){a.setContext("onsiteads",{customObject:b.customObject});var c=a.getContext("page")||{};c.customObject=ATInternet.Utils.completeFstLevelObj(c.customObject,b.customObject,!1);a.setContext("page",c)}a.dispatchSubscribe("onSiteAds")};
    a.selfPromotion=this.selfPromotion={};a.publisher=this.publisher={};a.publisher.set=this.publisher.set=function(a){m(a,"publisher")};a.selfPromotion.set=this.selfPromotion.set=function(a){m(a,"selfPromotion")};a.publisher.add=this.publisher.add=function(f){b(k(f,"impression"),"publisher");a.dispatchSubscribe("onSiteAds")};a.selfPromotion.add=this.selfPromotion.add=function(f){b(k(f,"impression"),"selfPromotion");a.dispatchSubscribe("onSiteAds")};var d=this.advertEvent=function(b){var d=!0;a.exec("TechClicks",
        "manageClick",[b.elem,b.event],function(a){d=a});b.click?p(b):b.impression&&g(b);return d};a.publisher.send=this.publisher.send=function(a){return d(a)};a.selfPromotion.send=this.selfPromotion.send=function(a){return d(a)};a.onSiteAds={};a.onSiteAds.onDispatch=this.onDispatch=function(b){if(!a.dispatchSubscribed("page")){var d=a.getContext("page")||{};a.setParam("type","AT",{hitType:["publisher","selfPromotion"]});a.getParam("atc")&&(a.setParam("patc",h(d),{hitType:["publisher","selfPromotion"]}),
        a.setParam("s2atc",d.level2||"",{hitType:["publisher","selfPromotion"]}));(d=a.getContext("onsiteads"))&&d.customObject&&a.setParam("stc",d.customObject,{encode:!0,hitType:["publisher","selfPromotion"]});a.sendHit(null,[["hitType",["publisher","selfPromotion"]]],b)}};a.plugins.waitForDependencies(["Utils","TechClicks"],function(){e=document.location.href;a.plugins.exec("Utils","getQueryStringValue",["xtatc",e],function(b){b&&a.setParam("atc",b,{hitType:["publisher","selfPromotion","page"]})});a.emit("OnSiteAds:Ready",
        {lvl:"INFO",details:{href:e}})})};window.ATInternet.Tracker.addPlugin("OnSiteAds");
}).call(window);;(function(){var dfltPluginCfg={"info":true};var dfltGlobalCfg={};window.ATInternet.Tracker.Plugins.Page=function(a){var e=["pageId","chapterLabel","update"],h=["pid","pchap","pidt"],c=["page","site"],k=["f","x"],p=function(b){var f=b.name;a.exec("Utils","manageChapters",[b,"chapter",3],function(a){f=a+(f?f:"")});return f},g=function(a,b,f){b?a=b:a||"undefined"===typeof f||(a=f);return a},b=function(a,b,f){b.hasOwnProperty(f)&&(a[f]=g(a[f],b[f]))},m=function(b){if(!ATInternet.Utils.isPreview()||a.getConfig("preview"))ATInternet.Utils.isPrerender(function(a){b(a)})||
b()},d=function(b,f,d){if(f)for(var e=0;e<c.length;e++)if(f.hasOwnProperty(c[e])&&f[c[e]])for(var g in f[c[e]])f[c[e]].hasOwnProperty(g)&&(d?b[k[e]+g]=f[c[e]][g]:a.setParam(k[e]+g,f[c[e]][g]))},f=function(b,f,d){if(f){a.exec("Utils","manageChapters",[f,"chapter",3],function(a){a&&(f.chapterLabel=a.replace(/::$/gi,""))});for(var c=0;c<h.length;c++)f.hasOwnProperty(e[c])&&(d?b[h[c]]=f[e[c]]:a.setParam(h[c],f[e[c]]))}},r=function(b,f,d){if(f&&f.keywords instanceof Array){var c=f.keywords.length;if(0<
    c){for(var e="",g=0;g<c;g++)e+="["+f.keywords[g]+"]"+(g<c-1?"|":"");d?b.tag=e:a.setParam("tag",e)}}},n=function(b,f,d){if(f){var c,e=function(a){return a?a:"0"};c=""+(e(f.category1)+"-");c+=e(f.category2)+"-";c+=e(f.category3);d?b.ptype=c:a.setParam("ptype",c)}},l=function(b,f,d){if(f)for(var c in f)f.hasOwnProperty(c)&&"undefined"!==typeof f[c]&&(d?b[c]=f[c]:a.setParam(c,f[c]))};a.customVars=this.customVars={};a.customVars.set=this.customVars.set=function(b){var f=a.getContext("page")||{},d=f.customVars;
    if(d){if(b)for(var c in b)b.hasOwnProperty(c)&&(d[c]=ATInternet.Utils.completeFstLevelObj(d[c],b[c],!0))}else d=b;f.customVars=d;a.setContext("page",f)};a.dynamicLabel=this.dynamicLabel={};a.dynamicLabel.set=this.dynamicLabel.set=function(b){var f=a.getContext("page")||{};f.dynamicLabel=ATInternet.Utils.completeFstLevelObj(f.dynamicLabel,b,!0);a.setContext("page",f)};a.tags=this.tags={};a.tags.set=this.tags.set=function(b){var f=a.getContext("page")||{};f.tags=ATInternet.Utils.completeFstLevelObj(f.tags,
    b,!0);a.setContext("page",f)};a.customTreeStructure=this.customTreeStructure={};a.customTreeStructure.set=this.customTreeStructure.set=function(b){var f=a.getContext("page")||{};f.customTreeStructure=ATInternet.Utils.completeFstLevelObj(f.customTreeStructure,b,!0);a.setContext("page",f)};a.page={};a.page.reset=this.reset=function(){a.setContext("page",void 0)};a.page.set=this.set=function(f){a.dispatchSubscribe("page");var d=a.getContext("page")||{};d.name=g(d.name,f.name,"");d.level2=g(d.level2,
    f.level2,"");b(d,f,"chapter1");b(d,f,"chapter2");b(d,f,"chapter3");d.customObject=ATInternet.Utils.completeFstLevelObj(d.customObject,f.customObject,!0);a.setContext("page",d)};a.page.send=this.send=function(c){var e={p:p(c),s2:c.level2||""},k=!0,h=c.customObject;if(h){var s=a.getParam("stc",!0);if(s&&s.options.permanent){var v=s.options.hitType||[],x=ATInternet.Utils.arrayIndexOf;if(-1!==x(v,"page")||-1!==x(v,"all"))h=ATInternet.Utils.completeFstLevelObj(s.value||{},h,!0)}a.exec("Utils","customObjectToString",
    [h],function(a){e.stc=a})}h=a.getContext("page")||{};h.vrn&&(e.vrn=h.vrn,h.vrn=void 0,a.setContext("page",h));s=a.getContext("InternalSearch")||{};"undefined"!=typeof s.keyword&&(e.mc=ATInternet.Utils.cloneSimpleObject(s.keyword),"undefined"!=typeof s.resultPageNumber&&(e.np=ATInternet.Utils.cloneSimpleObject(s.resultPageNumber)),a.setContext("InternalSearch",void 0));ATInternet.Utils.isPreview()&&a.getConfig("preview")&&(e.pvw=1);d(e,c.customVars,!0);f(e,c.dynamicLabel,!0);r(e,c.tags,!0);n(e,c.customTreeStructure,
    !0);s=a.getContext("campaigns")||{};l(e,s,!0);a.setContext("campaigns",void 0);a.exec("TechClicks","manageClick",[c.elem,c.event],function(a){k=a});m(function(){a.sendHit(e,null,c.callback)});h.name=g(h.name,c.name,"");h.level2=g(h.level2,c.level2,"");b(h,c,"chapter1");b(h,c,"chapter2");b(h,c,"chapter3");a.setContext("page",h);return k};a.page.onDispatch=this.onDispatch=function(b){var c=a.getContext("page")||{},e=a.getContext("InternalSearch")||{};a.setParam("p",p(c));a.setParam("s2",c.level2||"");
    c.vrn&&(a.setParam("vrn",c.vrn),c.vrn=void 0,a.setContext("page",c));"undefined"!=typeof e.keyword&&(a.setParam("mc",ATInternet.Utils.cloneSimpleObject(e.keyword)),"undefined"!=typeof e.resultPageNumber&&a.setParam("np",ATInternet.Utils.cloneSimpleObject(e.resultPageNumber)),a.setContext("InternalSearch",void 0));ATInternet.Utils.isPreview()&&a.getConfig("preview")&&a.setParam("pvw",1);d(null,c.customVars,!1);f(null,c.dynamicLabel,!1);r(null,c.tags,!1);n(null,c.customTreeStructure,!1);e=a.getContext("campaigns")||
        {};l(null,e,!1);a.setContext("campaigns",void 0);var c=c.customObject,g=[["hitType",["page"]]];if(c)if(e=a.getParam("stc",!0)){var k=e.options.hitType||[],h=ATInternet.Utils.arrayIndexOf,h=-1!==h(k,"page")||-1!==h(k,"all"),k=e.options.permanent;h?(h=ATInternet.Utils.cloneSimpleObject(e),h.value=ATInternet.Utils.completeFstLevelObj(h.value||{},c,!0),a.setParam("stc",h.value,{encode:!0}),m(function(){a.sendHit(null,g,b)}),k&&a.setParam("stc",e.value,e.options)):(a.setParam("stc",c,{encode:!0}),m(function(){a.sendHit(null,
        g,b)}),a.setParam("stc",e.value,e.options))}else a.setParam("stc",c,{encode:!0}),m(function(){a.sendHit(null,g,b)});else m(function(){a.sendHit(null,g,b)})}};window.ATInternet.Tracker.addPlugin("Page");
}).call(window);;(function(){var dfltPluginCfg={"info":true};var dfltGlobalCfg={};window.ATInternet.Tracker.Plugins.RichMedia=function(a){var e=function(a,b){var d=parseInt(a,10);return d?Math.max(d,b):0},h=new function(){this._timeout={};this.setTimeout=function(b,d,c){this._timeout[b]=this._timeout[b]||{};window.clearTimeout(this._timeout[b][d]);this._timeout[b][d]=window.setTimeout(function(){a.richMedia.send({action:"refresh",playerId:b,mediaLabel:d})},1E3*c)};this.setTimeoutObject=function(b,d,c,g){this._timeout[b]=this._timeout[b]||{};if("undefined"===typeof this._timeout[b][d]){var k=
    [],h;for(h in c)c.hasOwnProperty(h)&&k.push({delay:e(h,0),refresh:e(c[h],5)});k.sort(function(a,b){return a.delay<b.delay?-1:a.delay>b.delay?1:0});this._timeout[b][d]={arrObj:k,arrObjSave:ATInternet.Utils.cloneSimpleObject(k)}}c=this._timeout[b][d];if(0<c.arrObj.length&&(k=c.arrObj[0].delay,h=c.arrObj[0].refresh,"number"===typeof k&&"number"===typeof h&&0<h)){c[k]=c[k]||{};var m=void 0;"undefined"!==typeof c.arrObj[1]&&(m=c.arrObj[1].delay);var p=0;"undefined"===typeof m?p=1:"number"===typeof c[k].num?
    p="refresh"===g?Math.max(c[k].num-1,0):c[k].num:"number"===typeof m&&(p=Math.floor(60*(m-k)/h)-1);c[k].num=p;window.clearTimeout(c[k].timeout);0<p?c[k].timeout=window.setTimeout(function(){a.richMedia.send({action:"refresh",playerId:b,mediaLabel:d})},1E3*h):(c[k].num=void 0,c[k].timeout=void 0,c.arrObj.splice(0,1),window.setTimeout(function(){a.richMedia.send({action:"refresh",playerId:b,mediaLabel:d})},1E3*h));this._timeout[b][d]=c}};this.clearTimeout=function(a,b,d){this._timeout[a]=this._timeout[a]||
    {};if("object"===typeof this._timeout[a][b]){for(var c in this._timeout[a][b])if(this._timeout[a][b].hasOwnProperty(c)){var e=this._timeout[a][b][c].num;"undefined"!==typeof e&&0<e&&(window.clearTimeout(this._timeout[a][b][c].timeout),this._timeout[a][b][c].timeout=void 0)}d&&(this._timeout[a][b].arrObj=ATInternet.Utils.cloneSimpleObject(this._timeout[a][b].arrObjSave))}else window.clearTimeout(this._timeout[a][b])};this.removePlayer=function(b){for(var d in this._timeout[b])this._timeout[b].hasOwnProperty(d)&&
(this.clearTimeout(b,d,!1),a.richMedia.send({action:"stop",playerId:b,mediaLabel:d}));this._timeout[b]={}};this.removeAll=function(){for(var a in this._timeout)this._timeout.hasOwnProperty(a)&&this.removePlayer(a);this._timeout={}}},c=new function(){this._media=function(){this.type=void 0;this.plyr=0;this.clnk=this.s2=void 0;this.p="";this.m9=this.m6=this.m5=this.m1=this.rfsh=this.buf=this.a=void 0};this._mediaAll={};this.setMediaProperty=function(a,b,d,c){this._mediaAll[a]=this._mediaAll[a]||{};
    this._mediaAll[a][b]=this._mediaAll[a][b]||new this._media;this._mediaAll[a][b][d]=c};this.getMediaProperty=function(a,b,d){if(this._mediaAll[a]&&this._mediaAll[a][b])return this._mediaAll[a][b][d]};this.removePlayer=function(a){this._mediaAll[a]={}};this.removeAll=function(){this._mediaAll={}}},k=function(b,d,c){var e=b[c]||"";a.exec("Utils","manageChapters",[b,d,3],function(a){e=a+e});return e},p=function(a,b,d,c){var e=a[b];"boolean"===typeof a[b]&&(e=a[b]?c:d);return e},g=function(a){var b=0;
    /^(\-|\+)?([0-9]+)$/.test(a)&&(b=Number(a));return b},b=function(a,b,d,e,g){b=c.getMediaProperty(b,d,e);"undefined"!==typeof b&&(a[e]=g?encodeURIComponent(b):b)},m=function(a,b,d){"undefined"!==typeof d&&(a[b]=d)},d=function(a,b,d,e){"undefined"!==typeof e&&c.setMediaProperty(a,b,d,e)};a.richMedia={};a.richMedia.add=this.add=function(a){a=a||{};var b=g(a.playerId),c=k(a,"mediaTheme","mediaLabel"),e=p(a,"isEmbedded","int","ext");d(b,c,"plyr",b);d(b,c,"type",a.mediaType);d(b,c,"s2",a.mediaLevel2);d(b,
    c,"p",c);d(b,c,"clnk",a.linkedContent||a.previousMedia);d(b,c,"a",a.action);d(b,c,"rfsh",a.refreshDuration);d(b,c,"m1",a.duration);d(b,c,"m5",e);d(b,c,"m6",a.broadcastMode);d(b,c,"m9",a.webdomain)};a.richMedia.remove=this.remove=function(a){h.removePlayer(a);c.removePlayer(a)};a.richMedia.removeAll=this.removeAll=function(){h.removeAll();c.removeAll()};a.richMedia.send=this.send=function(d){d=d||{};var r=g(d.playerId),n=k(d,"mediaTheme","mediaLabel"),l={};l.plyr=r;l.p=n;d.action&&(l.a=d.action);b(l,
    r,n,"type",!1);b(l,r,n,"s2",!1);b(l,r,n,"m1",!1);b(l,r,n,"m5",!1);b(l,r,n,"m6",!1);if("play"===l.a||"info"===l.a){d=p(d,"isBuffering","0","1");m(l,"buf",d);d=a.getContext("page")||{};var q=k(d,"chapter","name")||void 0;m(l,"prich",q);m(l,"s2rich",d.level2||void 0);b(l,r,n,"clnk",!1);b(l,r,n,"m9",!0)}a.sendHit(l,[["hitType",["richmedia"]]]);"pause"===l.a?h.clearTimeout(r,n,!1):"stop"===l.a&&h.clearTimeout(r,n,!0);if("play"===l.a||"refresh"===l.a)d=c.getMediaProperty(r,n,"rfsh"),"object"===typeof d?
    h.setTimeoutObject(r,n,d,l.a):(l=e(d,5),0!==l&&h.setTimeout(r,n,l))}};window.ATInternet.Tracker.addPlugin("RichMedia");
}).call(window);;(function(){var dfltPluginCfg={"clicksAutoManagementEnabled":true,"clicksAutoManagementTimeout":500,"info":false};var dfltGlobalCfg={};window.ATInternet.Tracker.Plugins.TechClicks=function(a){var e,h;a.configPlugin("TechClicks",dfltPluginCfg||{},function(a){e=a.clicksAutoManagementEnabled;h=a.clicksAutoManagementTimeout});this.deactivateAutoManagement=function(){e=!1};var c=function(a){switch(a.target){case "_top":window.top.location.href=a.url;break;case "_parent":window.parent.location.href=a.url;break;default:window.location.href=a.url}},k=function(a){var b=a.timeout;a.mailto?setTimeout(function(){window.location.href=a.mailto},
    b):a.form?setTimeout(function(){a.form.submit()},b):a.url&&setTimeout(function(){c({url:a.url,target:a.target})},b)},p=function(b){for(var e,g="_self",n=b.timeoutonly;b;){if(b.href&&0===b.href.indexOf("http")){e=b.href.split('"').join('\\"');g=b.target?b.target:g;break}b=b.parentNode}if(e){if(!n)a.onTrigger("Tracker:Hit:Sent:Ok",function(){c({url:e,target:g})});k({url:e,target:g,timeout:h})}},g=function(b){var c=b;for(b=c.timeoutonly;c&&"FORM"!==c.nodeName;)c=c.parentNode;if(c){if(!b)a.onTrigger("Tracker:Hit:Sent:Ok",
    function(){c.submit()});k({form:c,timeout:h})}},b=function(b){var c=b;for(b=c.timeoutonly;c&&!(c.href&&0<=c.href.indexOf("mailto:"));)c=c.parentNode;if(c){if(!b)a.onTrigger("Tracker:Hit:Sent:Ok",function(){window.location.href=c.href});k({mailto:c.href,timeout:h})}},m=function(a){for(;a;){if(a.href){if(0<=a.href.indexOf("mailto:"))return"mailto";if(0===a.href.indexOf("http"))return"redirection"}else if("FORM"===a.nodeName)return"form";a=a.parentNode}return""};this.manageClick=function(a,c){var k=
    !0;if(e&&a){var h;a:{for(h=a;h;){if("function"===typeof h.getAttribute&&("_blank"===h.getAttribute("target")||"no"===h.getAttribute("data-atclickmanagement"))){h=!0;break a}h=h.parentNode}h=a;for(var l=window.location.href,q;h;){if((q=h.href)&&0<=q.indexOf("#")&&l.substring(0,0<=l.indexOf("#")?l.indexOf("#"):l.length)===q.substring(0,q.indexOf("#"))){h=!0;break a}h=h.parentNode}h=!1}l=m(a);if(!h&&l)switch(l){case "mailto":b(a);k=!1;break;case "form":g(a);k=!1;break;case "redirection":p(a),k=!1}}c&&
(h=c.defaultPrevented,"function"===typeof c.isDefaultPrevented&&(h=c.isDefaultPrevented()),h||c.preventDefault&&c.preventDefault());return k}};window.ATInternet.Tracker.addPlugin("TechClicks");
}).call(window);;(function(){var dfltPluginCfg={"info":false};var dfltGlobalCfg={};window.ATInternet.Tracker.Plugins.Utils=function(a){var e=this,h={};e.getQueryStringValue=function(a,c){var e=window.ATInternet.Utils.hashcode(c).toString();if(!h[e]){h[e]={};var b=RegExp("[&#?]{1}([^&=#?]*)=([^&#]*)?","g"),m=b.exec(c);if(null!==m)for(;null!==m;)h[e][m[1]]=m[2],m=b.exec(c)}return h[e].hasOwnProperty(a)?h[e][a]:null};e.customObjectToString=function(a){return encodeURIComponent(window.ATInternet.Utils.jsonSerialize(a))};e.manageChapters=function(c,e,g){var b=a.getConfig("ignoreEmptyChapterValue"),
    h="";if(c){g=parseInt(g,10);for(var d=1;d<g+1;d++)var f=c[e+d]||"",h=b?h+(f?f+"::":""):h+(c.hasOwnProperty(e+d)?f+"::":"")}return h};e.getDocumentLevel=function(){var c=a.getConfig("documentLevel");if(0>c.indexOf("."))return window[c]||document;c=c.split(".");return window[c[0]][c[1]]||document};e.getLocation=function(){return e.getDocumentLevel().location.href};a.dispatchIndex={};a.dispatchStack=[];a.dispatchEventFor={};var c=0;a.dispatchSubscribe=function(c){return a.dispatchIndex[c]?!1:(a.dispatchStack.push(c),
    a.dispatchIndex[c]=!0)};a.dispatchSubscribed=function(c){return!0===a.dispatchIndex[c]};a.addSpecificDispatchEventFor=function(e){return a.dispatchEventFor[e]?!1:(a.dispatchEventFor[e]=!0,c++,!0)};a.processSpecificDispatchEventFor=function(e){a.dispatchEventFor[e]&&(a.dispatchEventFor[e]=!1,c--,0===c&&(a.dispatchEventFor={},a.emit("Tracker:Plugin:SpecificEvent:Exec:Complete",{lvl:"INFO"})))};a.dispatch=function(e){var h=function(){for(var b="",c=null;0<a.dispatchStack.length;)b=a.dispatchStack.pop(),
0===a.dispatchStack.length&&(c=e),a[b].onDispatch(c);a.dispatchIndex={};a.delContext(void 0,"customObject")},g=function(){if(a.plugins.isExecWaitingLazyloading())a.onTrigger("Tracker:Plugin:Lazyload:Exec:Complete",function(){h()},!0);else h()};if(0===c)g();else a.onTrigger("Tracker:Plugin:SpecificEvent:Exec:Complete",function(){g()},!0)};a.dispatchRedirect=function(c){var e=!0,g=null;c&&(c.elem&&(c.elem.timeoutonly=!0,a.plugins.exec("TechClicks","manageClick",[c.elem,c.event],function(a){e=a})),g=
    c.callback);a.dispatch(g);return e}};window.ATInternet.Tracker.addPlugin("Utils");
}).call(window);
if(typeof window.ATInternet.onTrackerLoad==='function'){window.ATInternet.onTrackerLoad();}