'use strict';(function(){(function(){var cmpScriptElement=document.createElement('script');var firstScript=document.getElementsByTagName('script')[0];cmpScriptElement.async=true;cmpScriptElement.type='text/javascript';var cmpVersion='https://quantcast.mgr.consensu.org/tcfv2/cmp2.js?referer=www.thelocal.de';cmpScriptElement.src=cmpVersion;window._qevents=window._qevents||[];(function(){var elem=document.createElement('script');elem.src=(document.location.protocol=="https:"?"https://secure":"http://edge")+".quantserve.com/quant.js";elem.async=true;elem.type="text/javascript";var scpt=document.getElementsByTagName('script')[0];scpt.parentNode.insertBefore(elem,scpt);})();var qcaccount='p-'+'Uznnx7uFLxujG';window._qevents.push({qacct:qcaccount,source:"choice"});firstScript.parentNode.insertBefore(cmpScriptElement,firstScript);})();(function(){var css=""
+" .qc-cmp-button { "
+"   background-color: #ED6C1F !important; "
+"   border-color: #ED6C1F !important; "
+" } "
+" .qc-cmp-button:hover { "
+"   border-color: #ED6C1F !important; "
+" } "
+" .qc-cmp-alt-action, "
+" .qc-cmp-link { "
+"   color: #ED6C1F !important; "
+" } "
+" .qc-cmp-button.qc-cmp-secondary-button:hover { "
+"   background-color: #ED6C1F !important; "
+"   border-color: #ED6C1F !important; "
+" } "
+" .qc-cmp-button { "
+"   color: #FFFFFF !important; "
+" } "
+" .qc-cmp-button.qc-cmp-secondary-button:hover { "
+"   color: #FFFFFF !important; "
+" } "
+" .qc-cmp-button.qc-cmp-secondary-button { "
+"   color: #FFFFFF !important; "
+" } "
+" .qc-cmp-button.qc-cmp-secondary-button { "
+"   background-color: #ED6C1F !important; "
+"   border-color: transparent !important; "
+" } "
+" .qc-cmp-ui, "
+" .qc-cmp-ui .qc-cmp-title, "
+" .qc-cmp-ui .qc-cmp-table, "
+" .qc-cmp-ui .qc-cmp-messaging, "
+" .qc-cmp-ui .qc-cmp-sub-title, "
+" .qc-cmp-ui .qc-cmp-vendor-list, "
+" .qc-cmp-ui .qc-cmp-purpose-info, "
+" .qc-cmp-ui .qc-cmp-table-header, "
+" .qc-cmp-ui .qc-cmp-beta-messaging, "
+" .qc-cmp-ui .qc-cmp-main-messaging, "
+" .qc-cmp-ui .qc-cmp-vendor-list-title{ "
+"   color: #424242 !important; "
+" } "
+" .qc-cmp-ui { "
+"   background-color: #FFFFFF !important; "
+" } "
+" .qc-cmp-small-toggle.qc-cmp-toggle-on, "
+" .qc-cmp-toggle.qc-cmp-toggle-on { "
+"   background-color: #ED6C1F!important; "
+"   border-color: #ED6C1F!important; "
+" } "
+".qc-cmp2-container .qc-cmp2-persistent-link {background-color: #424242;color: white;}"
+""
+"";var stylesElement=document.createElement('style');var re=new RegExp('&quote;','g');css=css.replace(re,'"');stylesElement.type='text/css';if(stylesElement.styleSheet){stylesElement.styleSheet.cssText=css;}else{stylesElement.appendChild(document.createTextNode(css));}
var head=document.head||document.getElementsByTagName('head')[0];head.appendChild(stylesElement);})();var autoDetectedLanguage='en';function splitLang(lang){return lang.length>2?lang.split('-')[0]:lang;};function isSupported(lang){var langs=['en','fr','de','it','es','da','nl','el','hu','pt','ro','fi','pl','sk','sv','no','ru','bg','ca','cs','et','hr','lt','lv','mt','sl','tr','zh'];return langs.indexOf(lang)===-1?false:true;};if(isSupported(splitLang(document.documentElement.lang))){autoDetectedLanguage=splitLang(document.documentElement.lang);}else if(isSupported(splitLang(navigator.language))){autoDetectedLanguage=splitLang(navigator.language);};var choiceMilliSeconds=(new Date).getTime();window.__tcfapi('init',2,function(){},{"coreConfig":{"uspVersion":1,"uspJurisdiction":["US"],"uspLspact":"N","suppressCcpaLinks":false,"quantcastAccountId":"Uznnx7uFLxujG","privacyMode":["GDPR","USP"],"hashCode":"Qn8RlbROlqXw8egfHV0sXA","publisherCountryCode":"SE","publisherName":"The Local Germany","vendorPurposeIds":[2,3,4,5,6,7,8,9,10,1],"vendorFeaturesIds":[1,3,2],"vendorPurposeLegitimateInterestIds":[2,3,4,5,6,7,8,9,10],"vendorSpecialFeaturesIds":[1,2],"vendorSpecialPurposesIds":[1,2],"googleEnabled":true,"consentScope":"service","thirdPartyStorageType":"iframe","consentOnSafari":false,"displayUi":"always","defaultToggleValue":"off","initScreenRejectButtonShowing":true,"softOptInEnabled":false,"showSummaryView":true,"persistentConsentLinkLocation":4,"displayPersistentConsentLink":true,"uiLayout":"popup","publisherLogo":"https://i.imgur.com/kDI94GJ.png","vendorListUpdateFreq":30,"publisherPurposeIds":[],"initScreenBodyTextOption":1,"publisherConsentRestrictionIds":[],"publisherLIRestrictionIds":[],"publisherPurposeLegitimateInterestIds":[],"publisherSpecialPurposesIds":[],"publisherFeaturesIds":[],"publisherSpecialFeaturesIds":[],"stacks":[1,42],"lang_":"en"},"premiumUiLabels":{"uspDnsText":[""]},"premiumProperties":{"nonIabVendorListUrl":"https://quantcast.mgr.consensu.org/choice/Uznnx7uFLxujG/www.thelocal.de/.well-known/noniab-vendorlist.json"},"coreUiLabels":{},"theme":{"uxPrimaryButtonTextColor":"#FFFFFF","uxPrimaryButtonColor":"#ED6C1F","uxBackgroundColor":"#FFFFFF","uxSecondaryButtonColor":"#ED6C1F","uxSecondaryButtonTextColor":"#FFFFFF","uxToogleActiveColor":"#ED6C1F","uxFontColor":"#424242"},'nonIabVendorsInfo':{"nonIabVendorList":[{"vendorId":1,"pCode":"Uznnx7uFLxujG","name":"Playad Media Group AB","privacyPolicyUrl":"http://playadmediagroup.com/privacy-data-protection/","nonIabPurposeConsentIds":[2,3,4],"nonIabPurposeLegitimateInterestIds":[]},{"vendorId":2,"pCode":"Uznnx7uFLxujG","name":"Carambola Media Ltd","privacyPolicyUrl":"https://www.carambola.com/privacyPolicy/index.html","nonIabPurposeConsentIds":[2,3,1,4,10,9,8,7,6,5],"nonIabPurposeLegitimateInterestIds":[]}],"nonIabVendorsHash":"70D73785DA9317DEC006CE5F571867C0","updateAt":"2021-05-06T09:49:27.061930Z"}});})();